title: Rezaul Karim | Research Scientist
description: Capable, efficient AI. Research in language and multimodal foundation models, computer vision, and AI that learns from experience.
url: https://rkyuca.github.io
baseurl: ""
author: Rezaul Karim
show_downloads: false
google_analytics: false
theme: jekyll-theme-cayman

twitter_username:
github_username: rkyuca
exclude:
  - README.md
  - README_back.md
  - script
  - docs
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-cayman.gemspec
